LOCAL_PATH := $(call my-dir)

# Install KernelAdiutor
include $(CLEAR_VARS)
LOCAL_MODULE := KernelAdiutor
LOCAL_SRC_FILES := $(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

# Install LMT Launcher
include $(CLEAR_VARS)
LOCAL_MODULE := LMT
LOCAL_SRC_FILES := $(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
$(shell mkdir -p $(TARGET_OUT_APPS_PRIVILEGED)/LMT/lib/arm)
$(shell cp $(LOCAL_PATH)/LMT/lib/arm/libTouchServiceNative.so $(TARGET_OUT_APPS_PRIVILEGED)/LMT/lib/arm/libTouchServiceNative.so)
ALL_DEFAULT_INSTALLED_MODULES += $(TARGET_OUT_APPS_PRIVILEGED)/LMT/lib/arm/libTouchServiceNative.so
include $(BUILD_PREBUILT)

# Install Viper4Android
include $(CLEAR_VARS)
LOCAL_MODULE := Viper4Android
LOCAL_SRC_FILES := $(LOCAL_MODULE)/$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

