LOCAL_PATH := $(call my-dir)

# Install BenzoBlock
include $(CLEAR_VARS)
LOCAL_MODULE := BenzoBlock
LOCAL_SRC_FILES := BenzoBlock/$(LOCAL_MODULE).apk
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_MODULE_TAGS := optional
include $(BUILD_PREBUILT)

# Install Gallery Next
include $(CLEAR_VARS)
LOCAL_MODULE := GalleryNext
LOCAL_OVERRIDES_PACKAGES := Gallery2
LOCAL_SRC_FILES := GalleryNext/$(LOCAL_MODULE).apk
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_MODULE_TAGS := optional
include $(BUILD_PREBUILT)
